# fly.toml app configuration file generated for glow-api-prod on 2024-09-20T14:35:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glow-api-prod'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/python/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
