app = 'glow-staging'
primary_region = 'sea'
kill_timeout = '5m0s'

[build]
  dockerfile = '../../Dockerfile'

[deploy]
  strategy = 'bluegreen'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  agent = 'python -m server.livekit_worker.main start'
  api = 'uvicorn server.api.main:app --host 0.0.0.0 --port 8000'

[http_service]
  internal_port = 8000
  force_https = true
  processes = ['api']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
  processes = ['agent']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['api']

# A check if required for the bluegreen deployment strategy.
[[checks]]
  processes = ["agent"]
  name = "healthcheck"
  port = 8081
  type = 'tcp'
  interval = '10s'
  timeout = '2s'
  grace_period = '5s'