name: CI
on: pull_request
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v4
        with:
          version: 8.11.0
      - name: Install dependencies
        run: pnpm install
      - name: Check GQL Types
        run: pnpm gql:check
      - name: Check Linter
        run: pnpm lint
      - name: Check Build
        run: pnpm build