name: Fly Deploy Staging
on:
  workflow_dispatch:
  pull_request:
    paths:
      - server/**
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-group
    environment:
      name: staging
      url: 'https://glow-staging.fly.dev'
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Run Database Migration
        run: npm run prisma:deploy
        env:
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
          DIRECT_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
      - name: Deploy Staging Environment
        id: deploy
        run: |
          flyctl deploy --remote-only \
            --config ops/fly/fly.staging.toml \
            --app glow-staging \
            --wait-timeout 900 \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_STAGING_API_KEY }}