name: Fly Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Run Database Migration
        run: npm run prisma:deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          DIRECT_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
      - run: |
          flyctl deploy --remote-only \
            --config ops/fly/fly.prod.toml \
            --app glow-api-prod \
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_PROD_API_TOKEN }}